// BioStream — design tokens for three directions
// A: Calm Editorial · B: Quiet Data · C: Soft Athletic

const DIRECTIONS = {
  A: {
    name: 'Calm Editorial',
    bg: '#f5f1ea',          // warm cream
    bgDeep: '#ebe5d9',
    surface: '#ffffff',
    surfaceAlt: '#faf6ee',
    ink: '#1a1a1a',
    inkSoft: '#3d3530',
    muted: '#7a6f60',
    line: '#e1d9c9',
    lineSoft: '#ede5d4',
    accent: '#c8553d',       // terracotta
    accentDeep: '#9c3e2b',
    accentSoft: '#f4d9cf',
    positive: '#5b7b3c',
    warm: '#d4a574',         // warm amber
    cool: '#7090a8',         // dusty blue
    serif: "'Fraunces', 'Cormorant Garamond', Georgia, serif",
    sans: "'Inter', -apple-system, system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
    radius: 16,
    radiusSm: 10,
    radiusLg: 24,
    shadowSm: '0 1px 2px rgba(60,40,20,0.04), 0 1px 1px rgba(60,40,20,0.04)',
    shadowMd: '0 8px 24px -8px rgba(60,40,20,0.12), 0 2px 6px rgba(60,40,20,0.04)',
  },
  B: {
    name: 'Quiet Data',
    bg: '#fafaf8',
    bgDeep: '#f0efea',
    surface: '#ffffff',
    surfaceAlt: '#f5f4f0',
    ink: '#0a0a0a',
    inkSoft: '#2a2a2a',
    muted: '#6a6a6a',
    line: '#e6e6e2',
    lineSoft: '#f0f0ec',
    accent: '#0a0a0a',       // ink as accent
    accentDeep: '#000',
    accentSoft: '#e8e8e4',
    positive: '#0a7a4a',
    warm: '#b8915a',
    cool: '#5a7a9a',
    serif: "'Newsreader', 'Charter', Georgia, serif",
    sans: "'Inter', -apple-system, system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
    radius: 8,
    radiusSm: 4,
    radiusLg: 12,
    shadowSm: '0 1px 0 rgba(0,0,0,0.04)',
    shadowMd: '0 1px 0 rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)',
  },
  C: {
    name: 'Soft Athletic',
    bg: '#eef2ee',
    bgDeep: '#dde6dd',
    surface: '#ffffff',
    surfaceAlt: '#f5f8f4',
    ink: '#0d1f1a',
    inkSoft: '#274432',
    muted: '#5a8071',
    line: '#cfdcd1',
    lineSoft: '#e0eae0',
    accent: '#1f5a3d',       // deep green
    accentDeep: '#0d3a23',
    accentSoft: '#cfe5d6',
    positive: '#3f8f5a',
    warm: '#d8a95e',
    cool: '#4a7a90',
    serif: "'Fraunces', Georgia, serif",
    sans: "'Inter', -apple-system, system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
    radius: 20,
    radiusSm: 12,
    radiusLg: 28,
    shadowSm: '0 1px 2px rgba(13,31,26,0.05)',
    shadowMd: '0 12px 32px -10px rgba(13,31,26,0.18), 0 2px 8px rgba(13,31,26,0.04)',
  },
};

// Persona presets — drive every screen's data
const PERSONAS = {
  peak: {
    name: 'Peak readiness',
    readiness: 92,
    readinessLabel: 'Primed',
    hrv: 78,
    hrvDelta: '+12',
    rhr: 48,
    rhrDelta: '-2',
    sleep: '7h 52m',
    sleepScore: 88,
    strain: 8.2,
    strainTarget: '14–16',
    recommendation: 'Hard intervals',
    recDetail: '6 × 800m at 5K pace · 45 min',
    recReason: 'HRV is up 12 ms over your 14-day baseline and your last hard session was 4 days ago. Today is a green light.',
    coachOpener: "You're primed. HRV bumped 12 ms overnight and RHR dropped to 48. If you've been waiting to push, this is the day.",
    color: 'positive',
    nextEvent: 'Half marathon · 6 weeks',
  },
  low: {
    name: 'Low recovery',
    readiness: 41,
    readinessLabel: 'Recover',
    hrv: 38,
    hrvDelta: '-18',
    rhr: 62,
    rhrDelta: '+8',
    sleep: '5h 14m',
    sleepScore: 52,
    strain: 14.6,
    strainTarget: '6–8',
    recommendation: 'Easy walk + mobility',
    recDetail: '30 min Z1 walk · 10 min hip mobility',
    recReason: 'HRV dropped 18 ms and RHR is elevated 8 bpm. Sleep was short. A hard session today would dig the hole deeper.',
    coachOpener: "I'd back off today. HRV's down sharply, sleep was short, and RHR is up. A walk and some mobility will pay back tomorrow.",
    color: 'warm',
    nextEvent: 'Half marathon · 6 weeks',
  },
  steady: {
    name: 'Steady state',
    readiness: 71,
    readinessLabel: 'Ready',
    hrv: 64,
    hrvDelta: '+2',
    rhr: 53,
    rhrDelta: '0',
    sleep: '7h 12m',
    sleepScore: 76,
    strain: 11.4,
    strainTarget: '10–12',
    recommendation: 'Tempo run',
    recDetail: '20 min warm-up · 25 min @ tempo · 10 min cool',
    recReason: 'You\'re in the green band. Building aerobic capacity here pays into your half marathon block.',
    coachOpener: "Solid baseline today. Your aerobic block calls for a tempo — let's get the 25 minutes in and bank it.",
    color: 'cool',
    nextEvent: 'Half marathon · 6 weeks',
  },
};

const GOALS = {
  run: { label: 'Improve running', icon: 'run', primary: 'Half marathon · Sept 14', detail: 'Build aerobic base, then sharpen' },
  muscle: { label: 'Build muscle', icon: 'dumbbell', primary: '+4 kg lean mass · 6 mo', detail: 'Progressive overload, 4×/wk' },
  fat: { label: 'Lose fat', icon: 'flame', primary: '−6 kg · 16 weeks', detail: 'Sustainable deficit, protect lean mass' },
  cycle: { label: 'Improve cycling', icon: 'bike', primary: 'Gran Fondo · Oct 12', detail: 'FTP build, long endurance' },
  event: { label: 'Train for event', icon: 'flag', primary: 'Tahoe Rim 50k · Aug', detail: 'Time on feet, climbing' },
  sleep: { label: 'Sleep & recovery', icon: 'moon', primary: '7.5 h / 85 score', detail: 'Consistency, low-stress training' },
  maintain: { label: 'Maintain fitness', icon: 'heart', primary: 'Stay sharp', detail: 'Mixed training, avoid plateau' },
};

window.DIRECTIONS = DIRECTIONS;
window.PERSONAS = PERSONAS;
window.GOALS = GOALS;
